server:
  port: ${SERVER_PORT:80}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-server:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

logging:
  level:
    com.dusk: ${LOGGING_LEVEL_CRUX:INFO}
