server:
  port: ${SERVER_PORT:53201}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript

spring:
  main:
    # 自动解析循环引用
    allow-circular-references: true
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  #阿里数据库连接池设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dusk}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:DuskTech@postgre}
    druid:
      max-active: 10
      min-idle: 2
      initial-size: 5
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        slf4j:
          statement-sql-pretty-format: true
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
          enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr:localhost:8848}
        username: ${spring.cloud.nacos.username:nacos}
        password: ${spring.cloud.nacos.password:dusk}
        namespace: sit
        group: services
      config:
        server-addr: ${NACOS_ADDRESS:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:dusk}
        namespace: sit
  flyway:
    enabled: false
    table: flyway_schema_history_auth

  data:
    redis:
      host: localhost
      password: DuskTech@redis
  mvc:
    async:
      request-timeout: 3600000
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}?namespace=${spring.cloud.nacos.discovery.namespace}
  scan:
    base-packages: com.dusk.module.auth.service
  consumer:
    check: false
  provider:
    timeout: 2000
app:
  use-redis: true
  #  是否强制过滤租户权限（租户admin拥有全部权限） 默认false
  disable-tenant-auth-filter: false
  login:
    #    登陆密码解密用国密4解密 默认得密钥是crux天下无敌得16进制转换
    encrypt-key: 63727578e5a4a9e4b88be697a0e6958c
  security:
    ignores: [ "/error/**","/swagger-resources/**","/swagger-ui.html","/v3/api-docs","/webjars/**","/login" ]
  #app消息推送
  notification:
    #就地部署
    local:
      enabled: ${APP_NOTIFICATION_LOCAL_ENABLE:false}
      publish-url: http://192.168.53.245:18090/notification/publish
      timeout: 2000


mqtt:
  is-enabled: false

# 这是单机配置，不适合集群
seata:
  enabled: false
  service:
    vgroup-mapping:
      dusk-module-auth-seata-service-group: default
    grouplist:
      default: 192.168.105.105:8091
#同步国网ISC数据
isc:
  sync:
    enable: false
    endpoint: "http://0.0.0.0:9000/iscService"
    defalut-password: asd!1234
    applications:
      - appid: ff8080817d30ce57017d310ce20b0000
        #租户名
        tenant-name: isc

#第三方单点登陆
sso:
  # 单点登陆时差 允许范围 单位分钟，对于无法校时的服务器（常见于内网服务器） 该值设置成999即可
  time-diff: 120


# 开启i国网单点登陆接口
igwsso:
  enable: false
  iscAppId: 6c6b24f2e7bb4d9d8ff155e12de2f622
  iscSecret: 897db13398fc4a17acc021e7d23a1222
  # 这里必须以“/”结尾
  address: https://igw.isgcc.net:18443/
  service: https://

## 消息推送配置
aliyun-push:
  iosAppKey: ${ALIYUN_PUSH_IOSAPPKEY:""}
  androidAppKey: ${ALIYUN_PUSH_ANDROIDAPPKEY:31911606}
springdoc:
  api-docs:
    enabled: ${swagger.enable}
  swagger-ui:
    enabled: ${swagger.enable}